# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:
{ flake.nixosModules.desktop-hardware =
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-90323e21-7fb7-489e-85ef-70402acda45f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-90323e21-7fb7-489e-85ef-70402acda45f".device = "/dev/disk/by-uuid/90323e21-7fb7-489e-85ef-70402acda45f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A97F-3E2E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
};
}
